build:
    build_starting:
        image: python:3.5.3-slim
        commands:
            - echo "Beginning new build"
    run_tests:
        image: python:3.5.3-slim
        commands:
            - pip install -r requirements.txt
            - pip install --upgrade pip


publish:
    docker:
        repo: $$DOCKER_USERNAME/apic_em_webapp
        tag: dev
        username: $$DOCKER_USERNAME
        password: $$DOCKER_PASSWORD
        email: $$DOCKER_EMAIL


notify:
    spark:
        image: hpreston/drone-spark
        auth_token: $$SPARK_TOKEN
        roomId: $$SPARK_ROOM
